api: 1
name: http-button
lang: c++

sources:
  - main.cpp

config:
  POLLING_INTERVAL:
    desc: The interval of polling a GPIO pin (in msec)
    type: int
    default: 1000
  SLACK_URL:
    desc: The Slack webhook URL
    type: string
  BUTTON_GPIO_PIN:
    desc: The digital GPIO pin to be polled
    type: int
